/*
 *  Copyright (C) 2005-2018 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

#include "InfoLabelRegistry.h"

#include "GUIInfoLabels.h"

using namespace KODI::GUILIB::GUIINFO;

// clang-format off

const std::unordered_map<std::string, int> CInfoLabelRegistry::s_labelMap = {
    // mediacontainer -> container.*
    {"container.hasfiles", CONTAINER_HASFILES},
    {"container.hasfolders", CONTAINER_HASFOLDERS},
    {"container.isstacked", CONTAINER_STACKED},
    {"container.folderpath", CONTAINER_FOLDERPATH},
    {"container.foldername", CONTAINER_FOLDERNAME},
    {"container.pluginname", CONTAINER_PLUGINNAME},
    {"container.plugincategory", CONTAINER_PLUGINCATEGORY},
    {"container.viewmode", CONTAINER_VIEWMODE},
    {"container.viewcount", CONTAINER_VIEWCOUNT},
    {"container.totaltime", CONTAINER_TOTALTIME},
    {"container.totalwatched", CONTAINER_TOTALWATCHED},
    {"container.totalunwatched", CONTAINER_TOTALUNWATCHED},
    {"container.hasthumb", CONTAINER_HAS_THUMB},
    {"container.sortorder", CONTAINER_SORT_ORDER},
    {"container.canfilter", CONTAINER_CAN_FILTER},
    {"container.canfilteradvanced", CONTAINER_CAN_FILTERADVANCED},
    {"container.filtered", CONTAINER_FILTERED},
    {"container.showplot", CONTAINER_SHOWPLOT},
    {"container.showtitle", CONTAINER_SHOWTITLE},

    // fanart_labels -> fanart.*
    {"fanart.color1", FANART_COLOR1},
    {"fanart.color2", FANART_COLOR2},
    {"fanart.color3", FANART_COLOR3},
    {"fanart.image", FANART_IMAGE},

    // musicpartymode -> musicpartymode.*
    {"musicpartymode.enabled", MUSICPM_ENABLED},
    {"musicpartymode.songsplayed", MUSICPM_SONGSPLAYED},
    {"musicpartymode.matchingsongs", MUSICPM_MATCHINGSONGS},
    {"musicpartymode.matchingsongspicked", MUSICPM_MATCHINGSONGSPICKED},
    {"musicpartymode.matchingsongsleft", MUSICPM_MATCHINGSONGSLEFT},
    {"musicpartymode.relaxedsongspicked", MUSICPM_RELAXEDSONGSPICKED},
    {"musicpartymode.randomsongspicked", MUSICPM_RANDOMSONGSPICKED},

    // network_labels -> network.*
    {"network.isdhcp", NETWORK_IS_DHCP},
    {"network.ipaddress", NETWORK_IP_ADDRESS},
    {"network.linkstate", NETWORK_LINK_STATE},
    {"network.macaddress", NETWORK_MAC_ADDRESS},
    {"network.subnetmask", NETWORK_SUBNET_MASK},
    {"network.gatewayaddress", NETWORK_GATEWAY_ADDRESS},
    {"network.dns1address", NETWORK_DNS1_ADDRESS},
    {"network.dns2address", NETWORK_DNS2_ADDRESS},

    // player_labels -> player.*
    {"player.hasmedia", PLAYER_HAS_MEDIA},
    {"player.hasaudio", PLAYER_HAS_AUDIO},
    {"player.hasvideo", PLAYER_HAS_VIDEO},
    {"player.hasgame", PLAYER_HAS_GAME},
    {"player.isexternal", PLAYER_IS_EXTERNAL},
    {"player.isremote", PLAYER_IS_REMOTE},
    {"player.islive", PLAYER_IS_LIVE},
    {"player.playing", PLAYER_PLAYING},
    {"player.paused", PLAYER_PAUSED},
    {"player.rewinding", PLAYER_REWINDING},
    {"player.forwarding", PLAYER_FORWARDING},
    {"player.rewinding2x", PLAYER_REWINDING_2x},
    {"player.rewinding4x", PLAYER_REWINDING_4x},
    {"player.rewinding8x", PLAYER_REWINDING_8x},
    {"player.rewinding16x", PLAYER_REWINDING_16x},
    {"player.rewinding32x", PLAYER_REWINDING_32x},
    {"player.forwarding2x", PLAYER_FORWARDING_2x},
    {"player.forwarding4x", PLAYER_FORWARDING_4x},
    {"player.forwarding8x", PLAYER_FORWARDING_8x},
    {"player.forwarding16x", PLAYER_FORWARDING_16x},
    {"player.forwarding32x", PLAYER_FORWARDING_32x},
    {"player.caching", PLAYER_CACHING},
    {"player.seekbar", PLAYER_SEEKBAR},
    {"player.seeking", PLAYER_SEEKING},
    {"player.showtime", PLAYER_SHOWTIME},
    {"player.showinfo", PLAYER_SHOWINFO},
    {"player.muted", PLAYER_MUTED},
    {"player.hasduration", PLAYER_HASDURATION},
    {"player.passthrough", PLAYER_PASSTHROUGH},
    {"player.cachelevel", PLAYER_CACHELEVEL},
    {"player.title", PLAYER_TITLE},
    {"player.progress", PLAYER_PROGRESS},
    {"player.progresscache", PLAYER_PROGRESS_CACHE},
    {"player.volume", PLAYER_VOLUME},
    {"player.subtitledelay", PLAYER_SUBTITLE_DELAY},
    {"player.audiodelay", PLAYER_AUDIO_DELAY},
    {"player.chapter", PLAYER_CHAPTER},
    {"player.chaptercount", PLAYER_CHAPTERCOUNT},
    {"player.chaptername", PLAYER_CHAPTERNAME},
    {"player.folderpath", PLAYER_PATH},
    {"player.filenameandpath", PLAYER_FILEPATH},
    {"player.filename", PLAYER_FILENAME},
    {"player.isinternetstream", PLAYER_ISINTERNETSTREAM},
    {"player.pauseenabled", PLAYER_CAN_PAUSE},
    {"player.seekenabled", PLAYER_CAN_SEEK},
    {"player.channelpreviewactive", PLAYER_IS_CHANNEL_PREVIEW_ACTIVE},
    {"player.tempoenabled", PLAYER_SUPPORTS_TEMPO},
    {"player.istempo", PLAYER_IS_TEMPO},
    {"player.playspeed", PLAYER_PLAYSPEED},
    {"player.hasprograms", PLAYER_HAS_PROGRAMS},
    {"player.hasresolutions", PLAYER_HAS_RESOLUTIONS},
    {"player.frameadvance", PLAYER_FRAMEADVANCE},
    {"player.icon", PLAYER_ICON},
    {"player.editlist", PLAYER_EDITLIST},
    {"player.cuts", PLAYER_CUTS},
    {"player.scenemarkers", PLAYER_SCENE_MARKERS},
    {"player.hasscenemarkers", PLAYER_HAS_SCENE_MARKERS},
    {"player.chapters", PLAYER_CHAPTERS},

    // pvr -> pvr.*
    {"pvr.isrecording", PVR_IS_RECORDING},
    {"pvr.hastimer", PVR_HAS_TIMER},
    {"pvr.hastvchannels", PVR_HAS_TV_CHANNELS},
    {"pvr.hasradiochannels", PVR_HAS_RADIO_CHANNELS},
    {"pvr.hasnonrecordingtimer", PVR_HAS_NONRECORDING_TIMER},
    {"pvr.backendname", PVR_BACKEND_NAME},
    {"pvr.backendversion", PVR_BACKEND_VERSION},
    {"pvr.backendhost", PVR_BACKEND_HOST},
    {"pvr.backenddiskspace", PVR_BACKEND_DISKSPACE},
    {"pvr.backenddiskspaceprogr", PVR_BACKEND_DISKSPACE_PROGR},
    {"pvr.backendchannels", PVR_BACKEND_CHANNELS},
    {"pvr.backendtimers", PVR_BACKEND_TIMERS},
    {"pvr.backendrecordings", PVR_BACKEND_RECORDINGS},
    {"pvr.backenddeletedrecordings", PVR_BACKEND_DELETED_RECORDINGS},
    {"pvr.backendnumber", PVR_BACKEND_NUMBER},
    {"pvr.totaldiscspace", PVR_TOTAL_DISKSPACE},
    {"pvr.nexttimer", PVR_NEXT_TIMER},
    {"pvr.isplayingtv", PVR_IS_PLAYING_TV},
    {"pvr.isplayingradio", PVR_IS_PLAYING_RADIO},
    {"pvr.isplayingrecording", PVR_IS_PLAYING_RECORDING},
    {"pvr.isplayingepgtag", PVR_IS_PLAYING_EPGTAG},
    {"pvr.epgeventprogress", PVR_EPG_EVENT_PROGRESS},
    {"pvr.actstreamclient", PVR_ACTUAL_STREAM_CLIENT},
    {"pvr.actstreamdevice", PVR_ACTUAL_STREAM_DEVICE},
    {"pvr.actstreamstatus", PVR_ACTUAL_STREAM_STATUS},
    {"pvr.actstreamsignal", PVR_ACTUAL_STREAM_SIG},
    {"pvr.actstreamsnr", PVR_ACTUAL_STREAM_SNR},
    {"pvr.actstreamber", PVR_ACTUAL_STREAM_BER},
    {"pvr.actstreamunc", PVR_ACTUAL_STREAM_UNC},
    {"pvr.actstreamprogrsignal", PVR_ACTUAL_STREAM_SIG_PROGR},
    {"pvr.actstreamprogrsnr", PVR_ACTUAL_STREAM_SNR_PROGR},
    {"pvr.actstreamisencrypted", PVR_ACTUAL_STREAM_ENCRYPTED},
    {"pvr.actstreamencryptionname", PVR_ACTUAL_STREAM_CRYPTION},
    {"pvr.actstreamservicename", PVR_ACTUAL_STREAM_SERVICE},
    {"pvr.actstreammux", PVR_ACTUAL_STREAM_MUX},
    {"pvr.actstreamprovidername", PVR_ACTUAL_STREAM_PROVIDER},
    {"pvr.istimeshift", PVR_IS_TIMESHIFTING},
    {"pvr.timeshiftprogress", PVR_TIMESHIFT_PROGRESS},
    {"pvr.timeshiftseekbar", PVR_TIMESHIFT_SEEKBAR},
    {"pvr.nowrecordingtitle", PVR_NOW_RECORDING_TITLE},
    {"pvr.nowrecordingdatetime", PVR_NOW_RECORDING_DATETIME},
    {"pvr.nowrecordingchannel", PVR_NOW_RECORDING_CHANNEL},
    {"pvr.nowrecordingchannelicon", PVR_NOW_RECORDING_CHAN_ICO},
    {"pvr.nextrecordingtitle", PVR_NEXT_RECORDING_TITLE},
    {"pvr.nextrecordingdatetime", PVR_NEXT_RECORDING_DATETIME},
    {"pvr.nextrecordingchannel", PVR_NEXT_RECORDING_CHANNEL},
    {"pvr.nextrecordingchannelicon", PVR_NEXT_RECORDING_CHAN_ICO},
    {"pvr.tvnowrecordingtitle", PVR_TV_NOW_RECORDING_TITLE},
    {"pvr.tvnowrecordingdatetime", PVR_TV_NOW_RECORDING_DATETIME},
    {"pvr.tvnowrecordingchannel", PVR_TV_NOW_RECORDING_CHANNEL},
    {"pvr.tvnowrecordingchannelicon", PVR_TV_NOW_RECORDING_CHAN_ICO},
    {"pvr.tvnextrecordingtitle", PVR_TV_NEXT_RECORDING_TITLE},
    {"pvr.tvnextrecordingdatetime", PVR_TV_NEXT_RECORDING_DATETIME},
    {"pvr.tvnextrecordingchannel", PVR_TV_NEXT_RECORDING_CHANNEL},
    {"pvr.tvnextrecordingchannelicon", PVR_TV_NEXT_RECORDING_CHAN_ICO},
    {"pvr.radionowrecordingtitle", PVR_RADIO_NOW_RECORDING_TITLE},
    {"pvr.radionowrecordingdatetime", PVR_RADIO_NOW_RECORDING_DATETIME},
    {"pvr.radionowrecordingchannel", PVR_RADIO_NOW_RECORDING_CHANNEL},
    {"pvr.radionowrecordingchannelicon", PVR_RADIO_NOW_RECORDING_CHAN_ICO},
    {"pvr.radionextrecordingtitle", PVR_RADIO_NEXT_RECORDING_TITLE},
    {"pvr.radionextrecordingdatetime", PVR_RADIO_NEXT_RECORDING_DATETIME},
    {"pvr.radionextrecordingchannel", PVR_RADIO_NEXT_RECORDING_CHANNEL},
    {"pvr.radionextrecordingchannelicon", PVR_RADIO_NEXT_RECORDING_CHAN_ICO},
    {"pvr.isrecordingtv", PVR_IS_RECORDING_TV},
    {"pvr.hastvtimer", PVR_HAS_TV_TIMER},
    {"pvr.hasnonrecordingtvtimer", PVR_HAS_NONRECORDING_TV_TIMER},
    {"pvr.isrecordingradio", PVR_IS_RECORDING_RADIO},
    {"pvr.hasradiotimer", PVR_HAS_RADIO_TIMER},
    {"pvr.hasnonrecordingradiotimer", PVR_HAS_NONRECORDING_RADIO_TIMER},
    {"pvr.channelnumberinput", PVR_CHANNEL_NUMBER_INPUT},
    {"pvr.canrecordplayingchannel", PVR_CAN_RECORD_PLAYING_CHANNEL},
    {"pvr.isrecordingplayingchannel", PVR_IS_RECORDING_PLAYING_CHANNEL},
    {"pvr.isplayingactiverecording", PVR_IS_PLAYING_ACTIVE_RECORDING},
    {"pvr.timeshiftprogressplaypos", PVR_TIMESHIFT_PROGRESS_PLAY_POS},
    {"pvr.timeshiftprogressepgstart", PVR_TIMESHIFT_PROGRESS_EPG_START},
    {"pvr.timeshiftprogressepgend", PVR_TIMESHIFT_PROGRESS_EPG_END},
    {"pvr.timeshiftprogressbufferstart", PVR_TIMESHIFT_PROGRESS_BUFFER_START},
    {"pvr.timeshiftprogressbufferend", PVR_TIMESHIFT_PROGRESS_BUFFER_END},
    {"pvr.epgeventicon", PVR_EPG_EVENT_ICON},
    {"pvr.clientcount", PVR_CLIENT_COUNT},
    {"pvr.clientname", PVR_CLIENT_NAME},
    {"pvr.instancename", PVR_INSTANCE_NAME},

    // rds -> rds.*
    {"rds.hasrds", RDS_HAS_RDS},
    {"rds.hasradiotext", RDS_HAS_RADIOTEXT},
    {"rds.hasradiotextplus", RDS_HAS_RADIOTEXT_PLUS},
    {"rds.audiolanguage", RDS_AUDIO_LANG},
    {"rds.channelcountry", RDS_CHANNEL_COUNTRY},
    {"rds.title", RDS_TITLE},
    {"rds.getline", RDS_GET_RADIOTEXT_LINE},
    {"rds.artist", RDS_ARTIST},
    {"rds.band", RDS_BAND},
    {"rds.composer", RDS_COMPOSER},
    {"rds.conductor", RDS_CONDUCTOR},
    {"rds.album", RDS_ALBUM},
    {"rds.tracknumber", RDS_ALBUM_TRACKNUMBER},
    {"rds.radiostyle", RDS_GET_RADIO_STYLE},
    {"rds.comment", RDS_COMMENT},
    {"rds.infonews", RDS_INFO_NEWS},
    {"rds.infonewslocal", RDS_INFO_NEWS_LOCAL},
    {"rds.infostock", RDS_INFO_STOCK},
    {"rds.infostocksize", RDS_INFO_STOCK_SIZE},
    {"rds.infosport", RDS_INFO_SPORT},
    {"rds.infosportsize", RDS_INFO_SPORT_SIZE},
    {"rds.infolottery", RDS_INFO_LOTTERY},
    {"rds.infolotterysize", RDS_INFO_LOTTERY_SIZE},
    {"rds.infoweather", RDS_INFO_WEATHER},
    {"rds.infoweathersize", RDS_INFO_WEATHER_SIZE},
    {"rds.infocinema", RDS_INFO_CINEMA},
    {"rds.infocinemasize", RDS_INFO_CINEMA_SIZE},
    {"rds.infohoroscope", RDS_INFO_HOROSCOPE},
    {"rds.infohoroscopesize", RDS_INFO_HOROSCOPE_SIZE},
    {"rds.infoother", RDS_INFO_OTHER},
    {"rds.infoothersize", RDS_INFO_OTHER_SIZE},
    {"rds.progstation", RDS_PROG_STATION},
    {"rds.prognow", RDS_PROG_NOW},
    {"rds.prognext", RDS_PROG_NEXT},
    {"rds.proghost", RDS_PROG_HOST},
    {"rds.progeditstaff", RDS_PROG_EDIT_STAFF},
    {"rds.proghomepage", RDS_PROG_HOMEPAGE},
    {"rds.progstyle", RDS_PROG_STYLE},
    {"rds.phonehotline", RDS_PHONE_HOTLINE},
    {"rds.phonestudio", RDS_PHONE_STUDIO},
    {"rds.smsstudio", RDS_SMS_STUDIO},
    {"rds.emailhotline", RDS_EMAIL_HOTLINE},
    {"rds.emailstudio", RDS_EMAIL_STUDIO},
    {"rds.hashotline", RDS_HAS_HOTLINE_DATA},
    {"rds.hasstudio", RDS_HAS_STUDIO_DATA},

    // retroplayer -> retroplayer.*
    {"retroplayer.videofilter", RETROPLAYER_VIDEO_FILTER},
    {"retroplayer.stretchmode", RETROPLAYER_STRETCH_MODE},
    {"retroplayer.videorotation", RETROPLAYER_VIDEO_ROTATION},

    // skin_labels -> skin.*
    {"skin.currenttheme", SKIN_THEME},
    {"skin.currentcolourtheme", SKIN_COLOUR_THEME},
    {"skin.aspectratio", SKIN_ASPECT_RATIO},
    {"skin.font", SKIN_FONT},

    // slideshow -> slideshow.*
    {"slideshow.ispaused", SLIDESHOW_ISPAUSED},
    {"slideshow.isactive", SLIDESHOW_ISACTIVE},
    {"slideshow.isvideo", SLIDESHOW_ISVIDEO},
    {"slideshow.israndom", SLIDESHOW_ISRANDOM},
    {"slideshow.filename", SLIDESHOW_FILE_NAME},
    {"slideshow.path", SLIDESHOW_FILE_PATH},
    {"slideshow.filesize", SLIDESHOW_FILE_SIZE},
    {"slideshow.filedate", SLIDESHOW_FILE_DATE},
    {"slideshow.slideindex", SLIDESHOW_INDEX},
    {"slideshow.resolution", SLIDESHOW_RESOLUTION},
    {"slideshow.slidecomment", SLIDESHOW_COMMENT},
    {"slideshow.colour", SLIDESHOW_COLOUR},
    {"slideshow.process", SLIDESHOW_PROCESS},
    {"slideshow.exiftime", SLIDESHOW_EXIF_DATE_TIME},
    {"slideshow.exifdate", SLIDESHOW_EXIF_DATE},
    {"slideshow.longexiftime", SLIDESHOW_EXIF_LONG_DATE_TIME},
    {"slideshow.longexifdate", SLIDESHOW_EXIF_LONG_DATE},
    {"slideshow.exifdescription", SLIDESHOW_EXIF_DESCRIPTION},
    {"slideshow.cameramake", SLIDESHOW_EXIF_CAMERA_MAKE},
    {"slideshow.cameramodel", SLIDESHOW_EXIF_CAMERA_MODEL},
    {"slideshow.exifcomment", SLIDESHOW_EXIF_COMMENT},
    {"slideshow.aperture", SLIDESHOW_EXIF_APERTURE},
    {"slideshow.focallength", SLIDESHOW_EXIF_FOCAL_LENGTH},
    {"slideshow.focusdistance", SLIDESHOW_EXIF_FOCUS_DIST},
    {"slideshow.exposure", SLIDESHOW_EXIF_EXPOSURE},
    {"slideshow.exposuretime", SLIDESHOW_EXIF_EXPOSURE_TIME},
    {"slideshow.exposurebias", SLIDESHOW_EXIF_EXPOSURE_BIAS},
    {"slideshow.exposuremode", SLIDESHOW_EXIF_EXPOSURE_MODE},
    {"slideshow.flashused", SLIDESHOW_EXIF_FLASH_USED},
    {"slideshow.whitebalance", SLIDESHOW_EXIF_WHITE_BALANCE},
    {"slideshow.lightsource", SLIDESHOW_EXIF_LIGHT_SOURCE},
    {"slideshow.meteringmode", SLIDESHOW_EXIF_METERING_MODE},
    {"slideshow.isoequivalence", SLIDESHOW_EXIF_ISO_EQUIV},
    {"slideshow.digitalzoom", SLIDESHOW_EXIF_DIGITAL_ZOOM},
    {"slideshow.ccdwidth", SLIDESHOW_EXIF_CCD_WIDTH},
    {"slideshow.orientation", SLIDESHOW_EXIF_ORIENTATION},
    {"slideshow.supplementalcategories", SLIDESHOW_IPTC_SUP_CATEGORIES},
    {"slideshow.keywords", SLIDESHOW_IPTC_KEYWORDS},
    {"slideshow.caption", SLIDESHOW_IPTC_CAPTION},
    {"slideshow.author", SLIDESHOW_IPTC_AUTHOR},
    {"slideshow.headline", SLIDESHOW_IPTC_HEADLINE},
    {"slideshow.specialinstructions", SLIDESHOW_IPTC_SPEC_INSTR},
    {"slideshow.category", SLIDESHOW_IPTC_CATEGORY},
    {"slideshow.byline", SLIDESHOW_IPTC_BYLINE},
    {"slideshow.bylinetitle", SLIDESHOW_IPTC_BYLINE_TITLE},
    {"slideshow.credit", SLIDESHOW_IPTC_CREDIT},
    {"slideshow.source", SLIDESHOW_IPTC_SOURCE},
    {"slideshow.copyrightnotice", SLIDESHOW_IPTC_COPYRIGHT_NOTICE},
    {"slideshow.objectname", SLIDESHOW_IPTC_OBJECT_NAME},
    {"slideshow.city", SLIDESHOW_IPTC_CITY},
    {"slideshow.state", SLIDESHOW_IPTC_STATE},
    {"slideshow.country", SLIDESHOW_IPTC_COUNTRY},
    {"slideshow.transmissionreference", SLIDESHOW_IPTC_TX_REFERENCE},
    {"slideshow.iptcdate", SLIDESHOW_IPTC_DATE},
    {"slideshow.urgency", SLIDESHOW_IPTC_URGENCY},
    {"slideshow.countrycode", SLIDESHOW_IPTC_COUNTRY_CODE},
    {"slideshow.referenceservice", SLIDESHOW_IPTC_REF_SERVICE},
    {"slideshow.latitude", SLIDESHOW_EXIF_GPS_LATITUDE},
    {"slideshow.longitude", SLIDESHOW_EXIF_GPS_LONGITUDE},
    {"slideshow.altitude", SLIDESHOW_EXIF_GPS_ALTITUDE},
    {"slideshow.timecreated", SLIDESHOW_IPTC_TIMECREATED},
    {"slideshow.sublocation", SLIDESHOW_IPTC_SUBLOCATION},
    {"slideshow.imagetype", SLIDESHOW_IPTC_IMAGETYPE},

    // system_labels -> system.*
    {"system.hasnetwork", SYSTEM_ETHERNET_LINK_ACTIVE},
    {"system.hasmediadvd", SYSTEM_MEDIA_DVD},
    {"system.hasmediaaudiocd", SYSTEM_MEDIA_AUDIO_CD},
    {"system.hasmediablurayplaylist", SYSTEM_MEDIA_BLURAY_PLAYLIST},
    {"system.dvdready", SYSTEM_DVDREADY},
    {"system.trayopen", SYSTEM_TRAYOPEN},
    {"system.haslocks", SYSTEM_HASLOCKS},
    {"system.hashiddeninput", SYSTEM_HAS_INPUT_HIDDEN},
    {"system.hasloginscreen", SYSTEM_HAS_LOGINSCREEN},
    {"system.hasactivemodaldialog", SYSTEM_HAS_ACTIVE_MODAL_DIALOG},
    {"system.hasvisiblemodaldialog", SYSTEM_HAS_VISIBLE_MODAL_DIALOG},
    {"system.ismaster", SYSTEM_ISMASTER},
    {"system.isfullscreen", SYSTEM_ISFULLSCREEN},
    {"system.isstandalone", SYSTEM_ISSTANDALONE},
    {"system.loggedon", SYSTEM_LOGGEDON},
    {"system.showexitbutton", SYSTEM_SHOW_EXIT_BUTTON},
    {"system.canpowerdown", SYSTEM_CAN_POWERDOWN},
    {"system.cansuspend", SYSTEM_CAN_SUSPEND},
    {"system.canhibernate", SYSTEM_CAN_HIBERNATE},
    {"system.canreboot", SYSTEM_CAN_REBOOT},
    {"system.screensaveractive", SYSTEM_SCREENSAVER_ACTIVE},
    {"system.dpmsactive", SYSTEM_DPMS_ACTIVE},
    {"system.cputemperature", SYSTEM_CPU_TEMPERATURE},
    {"system.cpuusage", SYSTEM_CPU_USAGE},
    {"system.gputemperature", SYSTEM_GPU_TEMPERATURE},
    {"system.fanspeed", SYSTEM_FAN_SPEED},
    {"system.freespace", SYSTEM_FREE_SPACE},
    {"system.usedspace", SYSTEM_USED_SPACE},
    {"system.totalspace", SYSTEM_TOTAL_SPACE},
    {"system.usedspacepercent", SYSTEM_USED_SPACE_PERCENT},
    {"system.freespacepercent", SYSTEM_FREE_SPACE_PERCENT},
    {"system.buildversion", SYSTEM_BUILD_VERSION},
    {"system.buildversionshort", SYSTEM_BUILD_VERSION_SHORT},
    {"system.buildversioncode", SYSTEM_BUILD_VERSION_CODE},
    {"system.buildversiongit", SYSTEM_BUILD_VERSION_GIT},
    {"system.builddate", SYSTEM_BUILD_DATE},
    {"system.fps", SYSTEM_FPS},
    {"system.freememory", SYSTEM_FREE_MEMORY},
    {"system.language", SYSTEM_LANGUAGE},
    {"system.temperatureunits", SYSTEM_TEMPERATURE_UNITS},
    {"system.screenmode", SYSTEM_SCREEN_MODE},
    {"system.screenwidth", SYSTEM_SCREEN_WIDTH},
    {"system.screenheight", SYSTEM_SCREEN_HEIGHT},
    {"system.currentwindow", SYSTEM_CURRENT_WINDOW},
    {"system.currentcontrol", SYSTEM_CURRENT_CONTROL},
    {"system.currentcontrolid", SYSTEM_CURRENT_CONTROL_ID},
    {"system.dvdlabel", SYSTEM_DVD_LABEL},
    {"system.internetstate", SYSTEM_INTERNET_STATE},
    {"system.osversioninfo", SYSTEM_OS_VERSION_INFO},
    {"system.kernelversion", SYSTEM_OS_VERSION_INFO},
    {"system.uptime", SYSTEM_UPTIME},
    {"system.totaluptime", SYSTEM_TOTALUPTIME},
    {"system.cpufrequency", SYSTEM_CPUFREQUENCY},
    {"system.screenresolution", SYSTEM_SCREEN_RESOLUTION},
    {"system.videoencoderinfo", SYSTEM_VIDEO_ENCODER_INFO},
    {"system.profilename", SYSTEM_PROFILENAME},
    {"system.profilethumb", SYSTEM_PROFILETHUMB},
    {"system.profilecount", SYSTEM_PROFILECOUNT},
    {"system.profileautologin", SYSTEM_PROFILEAUTOLOGIN},
    {"system.progressbar", SYSTEM_PROGRESS_BAR},
    {"system.batterylevel", SYSTEM_BATTERY_LEVEL},
    {"system.friendlyname", SYSTEM_FRIENDLY_NAME},
    {"system.alarmpos", SYSTEM_ALARM_POS},
    {"system.isinhibit", SYSTEM_IDLE_SHUTDOWN_INHIBITED},
    {"system.idleshutdowninhibited", SYSTEM_IDLE_SHUTDOWN_INHIBITED},
    {"system.hasshutdown", SYSTEM_HAS_SHUTDOWN},
    {"system.haspvr", SYSTEM_HAS_PVR},
    {"system.startupwindow", SYSTEM_STARTUP_WINDOW},
    {"system.stereoscopicmode", SYSTEM_STEREOSCOPIC_MODE},
    {"system.hascms", SYSTEM_HAS_CMS},
    {"system.privacypolicy", SYSTEM_PRIVACY_POLICY},
    {"system.haspvraddon", SYSTEM_HAS_PVR_ADDON},
    {"system.addonupdatecount", SYSTEM_ADDON_UPDATE_COUNT},
    {"system.supportscpuusage", SYSTEM_SUPPORTS_CPU_USAGE},
    {"system.supportedhdrtypes", SYSTEM_SUPPORTED_HDR_TYPES},
    {"system.isscreensaverinhibited", SYSTEM_IS_SCREENSAVER_INHIBITED},

    // visualisation -> visualisation.*
    {"visualisation.locked", VISUALISATION_LOCKED},
    {"visualisation.preset", VISUALISATION_PRESET},
    {"visualisation.haspresets", VISUALISATION_HAS_PRESETS},
    {"visualisation.name", VISUALISATION_NAME},
    {"visualisation.enabled", VISUALISATION_ENABLED},

    // weather -> weather.*
    {"weather.isfetched", WEATHER_IS_FETCHED},
    {"weather.isupdating", WEATHER_IS_UPDATING},
    {"weather.lastupdated", WEATHER_LAST_UPDATED},
    {"weather.data", WEATHER_DATA},
    {"weather.conditions", WEATHER_CONDITIONS_TEXT},
    {"weather.temperature", WEATHER_TEMPERATURE},
    {"weather.location", WEATHER_LOCATION},
    {"weather.fanartcode", WEATHER_FANART_CODE},
    {"weather.plugin", WEATHER_PLUGIN},
    {"weather.conditionsicon", WEATHER_CONDITIONS_ICON},

    // system.platform.* (3-level paths)
    {"system.platform.linux", SYSTEM_PLATFORM_LINUX},
    {"system.platform.windows", SYSTEM_PLATFORM_WINDOWS},
    {"system.platform.uwp", SYSTEM_PLATFORM_UWP},
    {"system.platform.darwin", SYSTEM_PLATFORM_DARWIN},
    {"system.platform.osx", SYSTEM_PLATFORM_DARWIN_OSX},
    {"system.platform.ios", SYSTEM_PLATFORM_DARWIN_IOS},
    {"system.platform.tvos", SYSTEM_PLATFORM_DARWIN_TVOS},
    {"system.platform.android", SYSTEM_PLATFORM_ANDROID},
    {"system.platform.webos", SYSTEM_PLATFORM_WEBOS},

    // library.* (simple booleans)
    {"library.isscanning", LIBRARY_IS_SCANNING},
    {"library.isscanningvideo", LIBRARY_IS_SCANNING_VIDEO},
    {"library.isscanningmusic", LIBRARY_IS_SCANNING_MUSIC},
};

const std::unordered_map<std::string, int> CInfoLabelRegistry::s_musicPlayerMap = {
    {"title", MUSICPLAYER_TITLE},
    {"album", MUSICPLAYER_ALBUM},
    {"artist", MUSICPLAYER_ARTIST},
    {"albumartist", MUSICPLAYER_ALBUM_ARTIST},
    {"year", MUSICPLAYER_YEAR},
    {"genre", MUSICPLAYER_GENRE},
    {"duration", MUSICPLAYER_DURATION},
    {"tracknumber", MUSICPLAYER_TRACK_NUMBER},
    {"cover", MUSICPLAYER_COVER},
    {"bitrate", MUSICPLAYER_BITRATE},
    {"playlistlength", MUSICPLAYER_PLAYLISTLEN},
    {"playlistposition", MUSICPLAYER_PLAYLISTPOS},
    {"channels", MUSICPLAYER_CHANNELS},
    {"bitspersample", MUSICPLAYER_BITSPERSAMPLE},
    {"samplerate", MUSICPLAYER_SAMPLERATE},
    {"codec", MUSICPLAYER_CODEC},
    {"discnumber", MUSICPLAYER_DISC_NUMBER},
    {"disctitle", MUSICPLAYER_DISC_TITLE},
    {"rating", MUSICPLAYER_RATING},
    {"ratingandvotes", MUSICPLAYER_RATING_AND_VOTES},
    {"userrating", MUSICPLAYER_USER_RATING},
    {"votes", MUSICPLAYER_VOTES},
    {"comment", MUSICPLAYER_COMMENT},
    {"mood", MUSICPLAYER_MOOD},
    {"contributors", MUSICPLAYER_CONTRIBUTORS},
    {"contributorandrole", MUSICPLAYER_CONTRIBUTOR_AND_ROLE},
    {"lyrics", MUSICPLAYER_LYRICS},
    {"playlistplaying", MUSICPLAYER_PLAYLISTPLAYING},
    {"exists", MUSICPLAYER_EXISTS},
    {"hasprevious", MUSICPLAYER_HASPREVIOUS},
    {"hasnext", MUSICPLAYER_HASNEXT},
    {"playcount", MUSICPLAYER_PLAYCOUNT},
    {"lastplayed", MUSICPLAYER_LASTPLAYED},
    {"channelname", MUSICPLAYER_CHANNEL_NAME},
    {"channellogo", MUSICPLAYER_CHANNEL_LOGO},
    {"channelnumberlabel", MUSICPLAYER_CHANNEL_NUMBER},
    {"channelgroup", MUSICPLAYER_CHANNEL_GROUP},
    {"dbid", MUSICPLAYER_DBID},
    {"property", MUSICPLAYER_PROPERTY},
    {"releasedate", MUSICPLAYER_RELEASEDATE},
    {"originaldate", MUSICPLAYER_ORIGINALDATE},
    {"bpm", MUSICPLAYER_BPM},
    {"ismultidisc", MUSICPLAYER_ISMULTIDISC},
    {"totaldiscs", MUSICPLAYER_TOTALDISCS},
    {"station", MUSICPLAYER_STATIONNAME},
    {"mediaproviders", MUSICPLAYER_MEDIAPROVIDERS},
};

const std::unordered_map<std::string, int> CInfoLabelRegistry::s_videoPlayerMap = {
    {"title", VIDEOPLAYER_TITLE},
    {"genre", VIDEOPLAYER_GENRE},
    {"country", VIDEOPLAYER_COUNTRY},
    {"originaltitle", VIDEOPLAYER_ORIGINALTITLE},
    {"director", VIDEOPLAYER_DIRECTOR},
    {"year", VIDEOPLAYER_YEAR},
    {"cover", VIDEOPLAYER_COVER},
    {"usingoverlays", VIDEOPLAYER_USING_OVERLAYS},
    {"isfullscreen", VIDEOPLAYER_ISFULLSCREEN},
    {"hasmenu", VIDEOPLAYER_HASMENU},
    {"playlistlength", VIDEOPLAYER_PLAYLISTLEN},
    {"playlistposition", VIDEOPLAYER_PLAYLISTPOS},
    {"plot", VIDEOPLAYER_PLOT},
    {"plotoutline", VIDEOPLAYER_PLOT_OUTLINE},
    {"episode", VIDEOPLAYER_EPISODE},
    {"season", VIDEOPLAYER_SEASON},
    {"rating", VIDEOPLAYER_RATING},
    {"ratingandvotes", VIDEOPLAYER_RATING_AND_VOTES},
    {"userrating", VIDEOPLAYER_USER_RATING},
    {"votes", VIDEOPLAYER_VOTES},
    {"tvshowtitle", VIDEOPLAYER_TVSHOW},
    {"premiered", VIDEOPLAYER_PREMIERED},
    {"studio", VIDEOPLAYER_STUDIO},
    {"mpaa", VIDEOPLAYER_MPAA},
    {"top250", VIDEOPLAYER_TOP250},
    {"cast", VIDEOPLAYER_CAST},
    {"castandrole", VIDEOPLAYER_CAST_AND_ROLE},
    {"artist", VIDEOPLAYER_ARTIST},
    {"album", VIDEOPLAYER_ALBUM},
    {"writer", VIDEOPLAYER_WRITER},
    {"tagline", VIDEOPLAYER_TAGLINE},
    {"hasinfo", VIDEOPLAYER_HAS_INFO},
    {"trailer", VIDEOPLAYER_TRAILER},
    {"videocodec", VIDEOPLAYER_VIDEO_CODEC},
    {"videoresolution", VIDEOPLAYER_VIDEO_RESOLUTION},
    {"videoaspect", VIDEOPLAYER_VIDEO_ASPECT},
    {"videobitrate", VIDEOPLAYER_VIDEO_BITRATE},
    {"audiocodec", VIDEOPLAYER_AUDIO_CODEC},
    {"audiochannels", VIDEOPLAYER_AUDIO_CHANNELS},
    {"audiobitrate", VIDEOPLAYER_AUDIO_BITRATE},
    {"audiolanguage", VIDEOPLAYER_AUDIO_LANG},
    {"hasteletext", VIDEOPLAYER_HASTELETEXT},
    {"lastplayed", VIDEOPLAYER_LASTPLAYED},
    {"playcount", VIDEOPLAYER_PLAYCOUNT},
    {"hassubtitles", VIDEOPLAYER_HASSUBTITLES},
    {"subtitlesenabled", VIDEOPLAYER_SUBTITLESENABLED},
    {"subtitleslanguage", VIDEOPLAYER_SUBTITLES_LANG},
    {"starttime", VIDEOPLAYER_STARTTIME},
    {"endtime", VIDEOPLAYER_ENDTIME},
    {"nexttitle", VIDEOPLAYER_NEXT_TITLE},
    {"nextgenre", VIDEOPLAYER_NEXT_GENRE},
    {"nextplot", VIDEOPLAYER_NEXT_PLOT},
    {"nextplotoutline", VIDEOPLAYER_NEXT_PLOT_OUTLINE},
    {"nextstarttime", VIDEOPLAYER_NEXT_STARTTIME},
    {"nextendtime", VIDEOPLAYER_NEXT_ENDTIME},
    {"nextduration", VIDEOPLAYER_NEXT_DURATION},
    {"channelname", VIDEOPLAYER_CHANNEL_NAME},
    {"channellogo", VIDEOPLAYER_CHANNEL_LOGO},
    {"channelnumberlabel", VIDEOPLAYER_CHANNEL_NUMBER},
    {"channelgroup", VIDEOPLAYER_CHANNEL_GROUP},
    {"hasepg", VIDEOPLAYER_HAS_EPG},
    {"parentalrating", VIDEOPLAYER_PARENTAL_RATING},
    {"parentalratingcode", VIDEOPLAYER_PARENTAL_RATING_CODE},
    {"parentalratingicon", VIDEOPLAYER_PARENTAL_RATING_ICON},
    {"parentalratingsource", VIDEOPLAYER_PARENTAL_RATING_SOURCE},
    {"isstereoscopic", VIDEOPLAYER_IS_STEREOSCOPIC},
    {"stereoscopicmode", VIDEOPLAYER_STEREOSCOPIC_MODE},
    {"canresumelivetv", VIDEOPLAYER_CAN_RESUME_LIVE_TV},
    {"imdbnumber", VIDEOPLAYER_IMDBNUMBER},
    {"episodename", VIDEOPLAYER_EPISODENAME},
    {"dbid", VIDEOPLAYER_DBID},
    {"uniqueid", VIDEOPLAYER_UNIQUEID},
    {"tvshowdbid", VIDEOPLAYER_TVSHOWDBID},
    {"audiostreamcount", VIDEOPLAYER_AUDIOSTREAMCOUNT},
    {"videostreamcount", VIDEOPLAYER_VIDEOSTREAMCOUNT},
    {"hdrtype", VIDEOPLAYER_HDR_TYPE},
    {"art", VIDEOPLAYER_ART},
    {"videoversionname", VIDEOPLAYER_VIDEOVERSION_NAME},
    {"hasvideoversions", VIDEOPLAYER_HAS_VIDEOVERSIONS},
    {"episodepart", VIDEOPLAYER_EPISODEPART},
    {"mediaproviders", VIDEOPLAYER_MEDIAPROVIDERS},
    {"titleextrainfo", VIDEOPLAYER_TITLE_EXTRAINFO},
    {"hdrdetail", VIDEOPLAYER_HDR_DETAIL},
};

const std::unordered_map<std::string, int> CInfoLabelRegistry::s_playerMap = {
    {"hasmedia", PLAYER_HAS_MEDIA},
    {"hasaudio", PLAYER_HAS_AUDIO},
    {"hasvideo", PLAYER_HAS_VIDEO},
    {"hasgame", PLAYER_HAS_GAME},
    {"isexternal", PLAYER_IS_EXTERNAL},
    {"isremote", PLAYER_IS_REMOTE},
    {"islive", PLAYER_IS_LIVE},
    {"playing", PLAYER_PLAYING},
    {"paused", PLAYER_PAUSED},
    {"rewinding", PLAYER_REWINDING},
    {"forwarding", PLAYER_FORWARDING},
    {"rewinding2x", PLAYER_REWINDING_2x},
    {"rewinding4x", PLAYER_REWINDING_4x},
    {"rewinding8x", PLAYER_REWINDING_8x},
    {"rewinding16x", PLAYER_REWINDING_16x},
    {"rewinding32x", PLAYER_REWINDING_32x},
    {"forwarding2x", PLAYER_FORWARDING_2x},
    {"forwarding4x", PLAYER_FORWARDING_4x},
    {"forwarding8x", PLAYER_FORWARDING_8x},
    {"forwarding16x", PLAYER_FORWARDING_16x},
    {"forwarding32x", PLAYER_FORWARDING_32x},
    {"caching", PLAYER_CACHING},
    {"seekbar", PLAYER_SEEKBAR},
    {"seeking", PLAYER_SEEKING},
    {"showtime", PLAYER_SHOWTIME},
    {"showinfo", PLAYER_SHOWINFO},
    {"muted", PLAYER_MUTED},
    {"hasduration", PLAYER_HASDURATION},
    {"passthrough", PLAYER_PASSTHROUGH},
    {"cachelevel", PLAYER_CACHELEVEL},
    {"title", PLAYER_TITLE},
    {"progress", PLAYER_PROGRESS},
    {"progresscache", PLAYER_PROGRESS_CACHE},
    {"volume", PLAYER_VOLUME},
    {"subtitledelay", PLAYER_SUBTITLE_DELAY},
    {"audiodelay", PLAYER_AUDIO_DELAY},
    {"chapter", PLAYER_CHAPTER},
    {"chaptercount", PLAYER_CHAPTERCOUNT},
    {"chaptername", PLAYER_CHAPTERNAME},
    {"folderpath", PLAYER_PATH},
    {"filenameandpath", PLAYER_FILEPATH},
    {"filename", PLAYER_FILENAME},
    {"isinternetstream", PLAYER_ISINTERNETSTREAM},
    {"pauseenabled", PLAYER_CAN_PAUSE},
    {"seekenabled", PLAYER_CAN_SEEK},
    {"channelpreviewactive", PLAYER_IS_CHANNEL_PREVIEW_ACTIVE},
    {"tempoenabled", PLAYER_SUPPORTS_TEMPO},
    {"istempo", PLAYER_IS_TEMPO},
    {"playspeed", PLAYER_PLAYSPEED},
    {"hasprograms", PLAYER_HAS_PROGRAMS},
    {"hasresolutions", PLAYER_HAS_RESOLUTIONS},
    {"frameadvance", PLAYER_FRAMEADVANCE},
    {"icon", PLAYER_ICON},
    {"editlist", PLAYER_EDITLIST},
    {"cuts", PLAYER_CUTS},
    {"scenemarkers", PLAYER_SCENE_MARKERS},
    {"hasscenemarkers", PLAYER_HAS_SCENE_MARKERS},
    {"chapters", PLAYER_CHAPTERS},
};

// clang-format on

int CInfoLabelRegistry::LookupLabel(const std::string& label)
{
  auto it = s_labelMap.find(label);
  return (it != s_labelMap.end()) ? it->second : 0;
}

int CInfoLabelRegistry::LookupMusicPlayerProperty(const std::string& property)
{
  auto it = s_musicPlayerMap.find(property);
  return (it != s_musicPlayerMap.end()) ? it->second : 0;
}

int CInfoLabelRegistry::LookupVideoPlayerProperty(const std::string& property)
{
  auto it = s_videoPlayerMap.find(property);
  return (it != s_videoPlayerMap.end()) ? it->second : 0;
}

int CInfoLabelRegistry::LookupPlayerProperty(const std::string& property)
{
  auto it = s_playerMap.find(property);
  return (it != s_playerMap.end()) ? it->second : 0;
}
